# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bd5e2a4032d5c8a31d2dcbc5971bac6eb7f4b4c4daec1cf6b1b4f2e0fabd11714851d663c92d4cb39fa33adc48a227c71b53f624471466e794e0ac9922ba440b

test:
  secret_key_base: 85578978e44c87b18de36d2640752ac73892c3de811bd2ecfe442bcf56762f24c5402f6ce6c4042401df7768ded90b2af05e72b1638a6f473fdfe2a964e94251

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
